### ISSUE TITLE
Checksum mismatch for version 1.0.0

### ISSUE THREAD

**Issue by uilianries** [dice-group/dice-template-library#25]
Hello!

I would like to understand why the sha256 of `https://github.com/dice-group/dice-template-library/archive/refs/tags/v1.0.0.tar.gz` is now presenting a different result.

Before: `485505ad3f9fb033083e2952bd8b4e68f6b4f123746b20f4ec3af46f4ce66cfe`
Now: `d0c75ec4861e2480dc7d6533125f9c2dfb3574fc2cffd15c66665b1cdfa66561`

#### Steps to reproduce:

```
wget https://github.com/dice-group/dice-template-library/archive/refs/tags/v1.0.0.tar.gz
sha256sum v1.0.0.tar.gz
```

Did you re-upload the same package?

**Comment by Clueliss** [comment]
Yeah sorry about that, the release was retagged at some point to fix some things in the commit history. I think this must have happened close to the release of v1.1.0.

It was retagged to a different commit with identical contents, so the difference is probably somewhere in the metadata.
Didn't think about that, sorry again.

**Comment by uilianries** [comment]
@Clueliss Thank you for quick answer! No problem at all, just to be sure that's not a security flaw or something! Cheers!
